### ISSUE TITLE
<Response [401]> while requesting transaction data

### ISSUE THREAD

**Issue by lynch1972** [alexgolec/tda-api#206] opened 2021-04-10 23:30 UTC
I keep getting this error when i request transaction data. For other requests where no Authrization is not needed work fine.
My request (not json) returns : <Response [401]>
 if i request the json, it returns: 

Traceback (most recent call last):
  File "C:/Users/pmcra/PycharmProjects/IB/TDA_Get_Transactions.py", line 37, in <module>
    data = get_transactions(accountId=tda_config.accountId, type='ALL', symbol='AMD', startDate=date_i, endDate=date_f)
  File "C:/Users/pmcra/PycharmProjects/IB/TDA_Get_Transactions.py", line 30, in get_transactions
    return requests.get(url, params=params).json()
  File "C:\Users\pmcra\Anaconda3\envs\IB_data\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\pmcra\Anaconda3\envs\IB_data\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\pmcra\Anaconda3\envs\IB_data\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\pmcra\Anaconda3\envs\IB_data\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 11 (char 11)

Any idea how to solve this problem?
Thanks in advance

**Comment by alexgolec** [comment] 2021-04-10 23:40
Issues are not an appropriate venue for support. Please visit our discord to ask the community for help:

https://discord.gg/nfrd9gh

Also closed as duplicate of #204

**Closed by alexgolec** 2021-04-10 23:40 UTC
