### ISSUE TITLE
StreamingClient raising 401 error

### ISSUE THREAD

**Issue by WilliamCVan** [alexgolec/tda-api#160] opened 2021-01-31 21:44 UTC
**Description of Bug**
I am unable to get the streaming code working like the example here: https://tda-api.readthedocs.io/en/latest/streaming.html. It keeps throwing a 401 error. 

I am able to run the "c = auth.client_from_token_file(token_path, api_key)" example which generates my token.pickle file, and display the price history. I then use that same token.pickle file for the streamingclient below.

**Code to Reproduce**
```
client = easy_client(
        api_key='mykey_from_td_developer_api',
        redirect_uri='http://localhost:8080',
        token_path='token.pickle')
stream_client = StreamClient(client, account_id=123412345) //actual td acct here

async def read_stream():
    await stream_client.login()
    await stream_client.quality_of_service(StreamClient.QOSLevel.EXPRESS)

    # Always add handlers before subscribing because many streams start sending
    # data immediately after success, and messages with no handlers are dropped.
    stream_client.add_nasdaq_book_handler(
            lambda msg: print(json.dumps(msg, indent=4)))
    await stream_client.nasdaq_book_subs(['GOOG'])

    while True:
        await stream_client.handle_message()

asyncio.run(read_stream())

```
**Error/Exception Log, If Applicable**
tda-api version 1.1.0
Loading token from file token.pickle
Appending @AMER.OAUTHAP to API key
Returning client loaded from token file 'token.pickle'
Req 1: GET to https://api.tdameritrade.com/v1/userprincipals, params={
    "apikey": "mykey_from_td_developer_api@AMER.OAUTHAP",
    "fields": "streamerConnectionInfo,streamerSubscriptionKeys"
}
Req 1: GET response: 401, content=
          \{
        "error":"Full authentication is required to access this resource"
      		}
          
Traceback (most recent call last):
  File "C:\Users\Admin\.conda\envs\PyTorchENV\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\.conda\envs\PyTorchENV\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:/1_repos/StockTrading/tdAmeritradeNWStream.py", line 43, in read_stream
    await stream_client.login()
  File "C:\Users\Admin\.conda\envs\PyTorchENV\lib\site-packages\tda\streaming.py", line 348, in login
    assert r.status_code == httpx.codes.OK, r.raise_for_status()
  File "C:\Users\Admin\.conda\envs\PyTorchENV\lib\site-packages\httpx\_models.py", line 841, in raise_for_status
    raise HTTPError(message, response=self)
httpx._exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tdameritrade.com/v1/userprincipals?apikey=mykey_from_td_developer_api%40AMER.OAUTHAP&fields=streamerConnectionInfo%2CstreamerSubscriptionKeys
For more information check: https://httpstatuses.com/401

**Comment by alexgolec** [comment] 2021-02-01 04:01
This looks like an authentication/application configuration issue. I'm afraid I can't reproduce, but you're welcome to join our discord server and ask for help: 

https://discord.gg/nfrd9gh

Meanwhile I'll be closing this issue unless discussion indicates this is a library issue.

**Closed by alexgolec** 2021-02-01 04:01 UTC
