### ISSUE TITLE
search_instruments symbol parameter string deconstruction issue

### ISSUE THREAD

**Issue by jporacledba** [alexgolec/tda-api#32] opened 2020-06-15 19:47 UTC
Hello.  When using the Client.search_instruments method with the 'symbol-search' projection, it appears as though the value of the symbol parameter is deconstructed into a list of characters.  
Code:
```
r = c.search_instruments(symbols="GOOG",projection=c.Instrument.Projection.SYMBOL_SEARCH);
assert r.ok, r.raise_for_status()
text = r.json()
print(text)
```

Result:
```
{'G': {'cusip': 'G3922B107', 'symbol': 'G', 'description': 'Genpact Limited Common Stock', 'exchange': 'NYSE', 'assetType': 'EQUITY'}, 'O': {'cusip': '756109104', 'symbol': 'O', 'description': 'Realty Income Corporation Common Stock', 'exchange': 'NYSE', 'assetType': 'EQUITY'}}
```

However, submitting the symbol as a list produces the correct result:
Code:
```
r = c.search_instruments(symbols=[ "GOOG" ],projection=c.Instrument.Projection.SYMBOL_SEARCH);
assert r.ok, r.raise_for_status()
text = r.json()
print(text)
 ```
Result:
```
{'GOOG': {'cusip': '02079K107', 'symbol': 'GOOG', 'description': 'Alphabet Inc. - Class C Capital Stock', 'exchange': 'NASDAQ', 'assetType': 'EQUITY'}}
```

Similar issue with the 'regexp-search' projection.  No results when submitting the search metadata as a string, but when the string is part of a list, the search works correctly.
Code:
```
r = c.search_instruments(symbols="GOO.*",projection=c.Instrument.Projection.SYMBOL_REGEX);
assert r.ok, r.raise_for_status()
text = r.json()
print(text) 
```

Result:
```
{}
```

Whereas when passed as a list, the search metadata performs correctly:
```
r = c.search_instruments(symbols=[ "GOO.*" ],projection=c.Instrument.Projection.SYMBOL_REGEX);
assert r.ok, r.raise_for_status()
text = r.json()
print(text)
```

Result:
```
{'GOOD': {'cusip': '376536108', 'symbol': 'GOOD', 'description': 'Gladstone Commercial Corporation - Real Estate Investment Trust', 'exchange': 'NASDAQ', 'assetType': 'EQUITY'}, 'GOOG': {'cusip': '02079K107', 'symbol': 'GOOG', 'description': 'Alphabet Inc. - Class C Capital Stock', 'exchange': 'NASDAQ', 'assetType': 'EQUITY'}, ...
```

Thanks for your help.

**Comment by jporacledba** [comment] 2020-06-15 22:22
After re-reading the case notes, I wonder if, really, this is just a documentation bug?  The code works properly when the input data is submitted as a list.  I just got confused because the official docs for the search instruments API, https://developer.tdameritrade.com/instruments/apis/get/instruments, imply that the symbol field is a simple text field as opposed to a required list (for the symbol_**s**_ parameter).   Anyway, just wanted to throw that out there in case its helpful.

**Comment by alexgolec** [comment] 2020-06-15 22:39
To be honest I made the conscious decision to require lists, thinking that it would be clear enough from the documentation and the code to understand. This hasn't been the case, however, and I've seen a lot of confusion around this point. 

I've filed this issue add this conversion: https://github.com/alexgolec/tda-api/issues/33

**Comment by alexgolec** [comment] 2020-06-15 23:18
Closing as duplicate of https://github.com/alexgolec/tda-api/issues/33

**Closed** 2020-06-15 23:18 UTC
